# MSG91 SendOTP Service
# Sends OTPs via MSG91's SendOTP API v5 using a pre-approved template.
# All API calls are server-side only — credentials never reach the client.

import logging
import httpx
from app.core.config import settings

logger = logging.getLogger(__name__)

MSG91_SEND_URL = "https://control.msg91.com/api/v5/otp"


async def send_otp_msg91(phone: str, otp: str) -> tuple[bool, str]:
    """
    Send an OTP SMS via MSG91 SendOTP API v5.
    Phone must be 10-digit Indian number without country code.
    OTP is generated by our system and passed to MSG91 for delivery.
    Returns (success: bool, message: str).
    """
    normalised = phone.lstrip("+").replace(" ", "")
    if not normalised.startswith("91"):
        normalised = "91" + normalised

    params = {
        "authkey": settings.MSG91_AUTH_KEY,
        "template_id": settings.MSG91_OTP_TEMPLATE_ID,
        "mobile": normalised,
    }
    try:
        async with httpx.AsyncClient(timeout=10) as client:
            resp = await client.post(
                MSG91_SEND_URL,
                params=params,
                json={"otp": otp},
                headers={"Content-Type": "application/json"},
            )
        data = resp.json()
        logger.info(f"[MSG91] send response: {data}")

        if data.get("type") == "success":
            return True, data.get("message", "OTP sent")
        else:
            error = data.get("message", "MSG91 OTP send failed")
            logger.warning(f"[MSG91] send error: {error}")
            return False, error
    except Exception as exc:
        logger.error(f"[MSG91] send_otp exception: {exc}")
        return False, str(exc)


async def verify_otp_msg91(access_token: str, otp: str) -> tuple[bool, str]:
    """
    Verify an OTP via MSG91 Widget API.
    access_token is returned by MSG91 widget after user enters OTP on client side.
    Returns (success: bool, message: str).
    """
    url = "https://api.msg91.com/api/v5/widget/verifyAccessToken"
    try:
        async with httpx.AsyncClient(timeout=10) as client:
            resp = await client.post(
                url,
                json={"authkey": settings.MSG91_AUTH_KEY, "access-token": access_token},
                headers={"Content-Type": "application/json"},
            )
        data = resp.json()
        logger.info(f"[MSG91] verify response: {data}")
        if data.get("type") == "success":
            return True, data.get("message", "OTP verified")
        else:
            error = data.get("message", "MSG91 OTP verification failed")
            logger.warning(f"[MSG91] verify error: {error}")
            return False, error
    except Exception as exc:
        logger.error(f"[MSG91] verify_otp exception: {exc}")
        return False, str(exc)
